Data Cleaning

In [159]:
import pandas as pd
from sklearn.impute import SimpleImputer

In [160]:
df = pd.read_csv('sample_dataset.csv')

In [161]:
dff = df.copy()

In [162]:
df.dtypes.value_counts()

float64    29
object      1
int64       1
Name: count, dtype: int64

In [163]:
df['area error'].value_counts()

area error
A    489
B      4
C      1
Name: count, dtype: int64

In [164]:
df.select_dtypes(include=['int64', 'float64'])

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,NaN,2019.0,0.16220,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,NaN,NaN,0.0869,0.07017,NaN,0.05667,...,23.41,158.80,1956.0,0.12380,0.1866,0.2416,0.1860,0.2750,NaN,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,NaN,NaN,NaN,0.05999,...,25.53,NaN,1709.0,0.14440,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,NaN,0.2597,0.09744,...,26.50,NaN,567.7,0.20980,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,NaN,NaN,NaN,0.13280,0.1980,NaN,0.1809,NaN,...,16.67,152.20,1575.0,0.13740,NaN,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,NaN,0.2439,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.2113,0.4107,0.2216,0.2060,0.07115,0
565,NaN,28.25,131.20,1261.0,0.09780,0.10340,0.1440,0.09791,0.1752,NaN,...,38.25,155.00,1731.0,0.11660,0.1922,0.3215,0.1628,0.2572,NaN,0
566,16.60,28.08,108.30,NaN,0.08455,0.10230,NaN,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,NaN,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.15200,0.2397,NaN,...,NaN,184.60,1821.0,0.16500,0.8681,0.9387,0.2650,0.4087,0.12400,0
568,7.76,NaN,47.92,181.0,0.05263,0.04362,0.0000,0.00000,0.1587,0.05884,...,30.37,59.16,NaN,0.08996,NaN,0.0000,0.0000,0.2871,0.07039,1

In [165]:
df.select_dtypes(exclude=['int64', 'float64'])

    area error
0            A
1            A
2            A
3            A
4          NaN
..         ...
564          A
565          A
566          A
567          A
568          A

[569 rows x 1 columns]

In [166]:
categotical_variables = df.select_dtypes(include=['object','category','bool']).columns
numerical_variables = df.select_dtypes(exclude = ['object','category','bool']).columns

In [167]:
categotical_variables

Index(['area error'], dtype='object')

In [168]:
numerical_variables

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'smoothness error',
       'compactness error', 'concavity error', 'concave points error',
       'symmetry error', 'fractal dimension error', 'worst radius',
       'worst texture', 'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension', 'target'],
      dtype='object')

In [169]:
x = df.iloc[:, 0:3]
x

     mean radius  mean texture  mean perimeter
0            NaN         10.38          122.80
1          20.57         17.77          132.90
2          19.69         21.25          130.00
3          11.42         20.38           77.58
4          20.29         14.34             NaN
..           ...           ...             ...
564        21.56         22.39          142.00
565          NaN         28.25          131.20
566        16.60         28.08          108.30
567        20.60         29.33          140.10
568         7.76           NaN           47.92

[569 rows x 3 columns]

In [170]:
x['mean radius'].mean()

14.059547717842323

Replace blanks with mean value

In [171]:
cleaner = SimpleImputer(strategy='mean')

In [172]:
cleaner.fit(x)

SimpleImputer()

In [173]:
cleaner.transform(x)

array([[ 14.05954772,  10.38      , 122.8       ],
       [ 20.57      ,  17.77      , 132.9       ],
       [ 19.69      ,  21.25      , 130.        ],
       ...,
       [ 16.6       ,  28.08      , 108.3       ],
       [ 20.6       ,  29.33      , 140.1       ],
       [  7.76      ,  19.31182927,  47.92      ]])

In [174]:
df1 = pd.DataFrame(cleaner.transform(x), columns=x.columns)
print(df1)

     mean radius  mean texture  mean perimeter
0      14.059548     10.380000      122.800000
1      20.570000     17.770000      132.900000
2      19.690000     21.250000      130.000000
3      11.420000     20.380000       77.580000
4      20.290000     14.340000       92.039025
..           ...           ...             ...
564    21.560000     22.390000      142.000000
565    14.059548     28.250000      131.200000
566    16.600000     28.080000      108.300000
567    20.600000     29.330000      140.100000
568     7.760000     19.311829       47.920000

[569 rows x 3 columns]

In [175]:
x['mean radius'].median()

13.28

In [176]:

df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,NaN,2019.0,0.16220,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,NaN,NaN,0.0869,0.07017,NaN,0.05667,...,23.41,158.80,1956.0,0.12380,0.1866,0.2416,0.1860,0.2750,NaN,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,NaN,NaN,NaN,0.05999,...,25.53,NaN,1709.0,0.14440,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,NaN,0.2597,0.09744,...,26.50,NaN,567.7,0.20980,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,NaN,NaN,NaN,0.13280,0.1980,NaN,0.1809,NaN,...,16.67,152.20,1575.0,0.13740,NaN,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,NaN,0.2439,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.2113,0.4107,0.2216,0.2060,0.07115,0
565,NaN,28.25,131.20,1261.0,0.09780,0.10340,0.1440,0.09791,0.1752,NaN,...,38.25,155.00,1731.0,0.11660,0.1922,0.3215,0.1628,0.2572,NaN,0
566,16.60,28.08,108.30,NaN,0.08455,0.10230,NaN,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,NaN,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.15200,0.2397,NaN,...,NaN,184.60,1821.0,0.16500,0.8681,0.9387,0.2650,0.4087,0.12400,0
568,7.76,NaN,47.92,181.0,0.05263,0.04362,0.0000,0.00000,0.1587,0.05884,...,30.37,59.16,NaN,0.08996,NaN,0.0000,0.0000,0.2871,0.07039,1

In [177]:
y = df.iloc[:,0:4]
y

     mean radius  mean texture  mean perimeter  mean area
0            NaN         10.38          122.80     1001.0
1          20.57         17.77          132.90     1326.0
2          19.69         21.25          130.00     1203.0
3          11.42         20.38           77.58      386.1
4          20.29         14.34             NaN        NaN
..           ...           ...             ...        ...
564        21.56         22.39          142.00     1479.0
565          NaN         28.25          131.20     1261.0
566        16.60         28.08          108.30        NaN
567        20.60         29.33          140.10     1265.0
568         7.76           NaN           47.92      181.0

[569 rows x 4 columns]

In [178]:
df.select_dtypes(include= ['float','int'])

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,NaN,2019.0,0.16220,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,NaN,NaN,0.0869,0.07017,NaN,0.05667,...,23.41,158.80,1956.0,0.12380,0.1866,0.2416,0.1860,0.2750,NaN,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,NaN,NaN,NaN,0.05999,...,25.53,NaN,1709.0,0.14440,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,NaN,0.2597,0.09744,...,26.50,NaN,567.7,0.20980,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,NaN,NaN,NaN,0.13280,0.1980,NaN,0.1809,NaN,...,16.67,152.20,1575.0,0.13740,NaN,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,NaN,0.2439,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.2113,0.4107,0.2216,0.2060,0.07115,0
565,NaN,28.25,131.20,1261.0,0.09780,0.10340,0.1440,0.09791,0.1752,NaN,...,38.25,155.00,1731.0,0.11660,0.1922,0.3215,0.1628,0.2572,NaN,0
566,16.60,28.08,108.30,NaN,0.08455,0.10230,NaN,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,NaN,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.15200,0.2397,NaN,...,NaN,184.60,1821.0,0.16500,0.8681,0.9387,0.2650,0.4087,0.12400,0
568,7.76,NaN,47.92,181.0,0.05263,0.04362,0.0000,0.00000,0.1587,0.05884,...,30.37,59.16,NaN,0.08996,NaN,0.0000,0.0000,0.2871,0.07039,1

In [179]:
y

     mean radius  mean texture  mean perimeter  mean area
0            NaN         10.38          122.80     1001.0
1          20.57         17.77          132.90     1326.0
2          19.69         21.25          130.00     1203.0
3          11.42         20.38           77.58      386.1
4          20.29         14.34             NaN        NaN
..           ...           ...             ...        ...
564        21.56         22.39          142.00     1479.0
565          NaN         28.25          131.20     1261.0
566        16.60         28.08          108.30        NaN
567        20.60         29.33          140.10     1265.0
568         7.76           NaN           47.92      181.0

[569 rows x 4 columns]

In [180]:
cleanerm = SimpleImputer(strategy = 'median')

In [181]:
cleanerm.fit(y)

SimpleImputer(strategy='median')

In [182]:
df2 = pd.DataFrame(cleanerm.transform(y), columns=y.columns)

In [183]:
df2

     mean radius  mean texture  mean perimeter  mean area
0          13.28         10.38          122.80     1001.0
1          20.57         17.77          132.90     1326.0
2          19.69         21.25          130.00     1203.0
3          11.42         20.38           77.58      386.1
4          20.29         14.34           86.34      556.7
..           ...           ...             ...        ...
564        21.56         22.39          142.00     1479.0
565        13.28         28.25          131.20     1261.0
566        16.60         28.08          108.30      556.7
567        20.60         29.33          140.10     1265.0
568         7.76         18.86           47.92      181.0

[569 rows x 4 columns]

#For categorical value

In [184]:
df['area error'].isnull().sum()

75

In [185]:
cleanerf = SimpleImputer(strategy='most_frequent')
cleanerf.fit(df[['area error']])
df3 = pd.DataFrame(cleanerf.transform(df[['area error']]), columns=['area error'])

In [186]:
df3

    area error
0            A
1            A
2            A
3            A
4            A
..         ...
564          A
565          A
566          A
567          A
568          A

[569 rows x 1 columns]

In [187]:
cleanerf = SimpleImputer(strategy='constant', fill_value='-')
cleanerf.fit(df[['area error']])
df4 = pd.DataFrame(cleanerf.transform(df[['area error']]), columns=['area error'])

In [188]:
df4

    area error
0            A
1            A
2            A
3            A
4            -
..         ...
564          A
565          A
566          A
567          A
568          A

[569 rows x 1 columns]

In [189]:
dff

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,NaN,2019.0,0.16220,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,NaN,NaN,0.0869,0.07017,NaN,0.05667,...,23.41,158.80,1956.0,0.12380,0.1866,0.2416,0.1860,0.2750,NaN,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,NaN,NaN,NaN,0.05999,...,25.53,NaN,1709.0,0.14440,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,NaN,0.2597,0.09744,...,26.50,NaN,567.7,0.20980,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,NaN,NaN,NaN,0.13280,0.1980,NaN,0.1809,NaN,...,16.67,152.20,1575.0,0.13740,NaN,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,NaN,0.2439,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.2113,0.4107,0.2216,0.2060,0.07115,0
565,NaN,28.25,131.20,1261.0,0.09780,0.10340,0.1440,0.09791,0.1752,NaN,...,38.25,155.00,1731.0,0.11660,0.1922,0.3215,0.1628,0.2572,NaN,0
566,16.60,28.08,108.30,NaN,0.08455,0.10230,NaN,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,NaN,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.15200,0.2397,NaN,...,NaN,184.60,1821.0,0.16500,0.8681,0.9387,0.2650,0.4087,0.12400,0
568,7.76,NaN,47.92,181.0,0.05263,0.04362,0.0000,0.00000,0.1587,0.05884,...,30.37,59.16,NaN,0.08996,NaN,0.0000,0.0000,0.2871,0.07039,1

In [190]:
x = df.iloc[:, 0:3]
x

     mean radius  mean texture  mean perimeter
0            NaN         10.38          122.80
1          20.57         17.77          132.90
2          19.69         21.25          130.00
3          11.42         20.38           77.58
4          20.29         14.34             NaN
..           ...           ...             ...
564        21.56         22.39          142.00
565          NaN         28.25          131.20
566        16.60         28.08          108.30
567        20.60         29.33          140.10
568         7.76           NaN           47.92

[569 rows x 3 columns]

#KNN Imputer

In [192]:
from sklearn.impute import KNNImputer

In [193]:
cleaner = KNNImputer(n_neighbors=5)
cleaner.fit(x)
df5 = pd.DataFrame(cleaner.transform(x), columns=x.columns)

In [194]:
df5

     mean radius  mean texture  mean perimeter
0        13.9636        10.380         122.800
1        20.5700        17.770         132.900
2        19.6900        21.250         130.000
3        11.4200        20.380          77.580
4        20.2900        14.340          89.442
..           ...           ...             ...
564      21.5600        22.390         142.000
565      15.9186        28.250         131.200
566      16.6000        28.080         108.300
567      20.6000        29.330         140.100
568       7.7600        20.014          47.920

[569 rows x 3 columns]

In [196]:
cleaner = KNNImputer(n_neighbors=5, weights='distance')
cleaner.fit(x)
df5 = pd.DataFrame(cleaner.transform(x), columns=x.columns)
df5

     mean radius  mean texture  mean perimeter
0      14.880101     10.380000      122.800000
1      20.570000     17.770000      132.900000
2      19.690000     21.250000      130.000000
3      11.420000     20.380000       77.580000
4      20.290000     14.340000       98.071286
..           ...           ...             ...
564    21.560000     22.390000      142.000000
565    12.846271     28.250000      131.200000
566    16.600000     28.080000      108.300000
567    20.600000     29.330000      140.100000
568     7.760000     24.629301       47.920000

[569 rows x 3 columns]

In [197]:
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,NaN,2019.0,0.16220,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,NaN,NaN,0.0869,0.07017,NaN,0.05667,...,23.41,158.80,1956.0,0.12380,0.1866,0.2416,0.1860,0.2750,NaN,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,NaN,NaN,NaN,0.05999,...,25.53,NaN,1709.0,0.14440,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,NaN,0.2597,0.09744,...,26.50,NaN,567.7,0.20980,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,NaN,NaN,NaN,0.13280,0.1980,NaN,0.1809,NaN,...,16.67,152.20,1575.0,0.13740,NaN,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,NaN,0.2439,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.2113,0.4107,0.2216,0.2060,0.07115,0
565,NaN,28.25,131.20,1261.0,0.09780,0.10340,0.1440,0.09791,0.1752,NaN,...,38.25,155.00,1731.0,0.11660,0.1922,0.3215,0.1628,0.2572,NaN,0
566,16.60,28.08,108.30,NaN,0.08455,0.10230,NaN,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,NaN,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.15200,0.2397,NaN,...,NaN,184.60,1821.0,0.16500,0.8681,0.9387,0.2650,0.4087,0.12400,0
568,7.76,NaN,47.92,181.0,0.05263,0.04362,0.0000,0.00000,0.1587,0.05884,...,30.37,59.16,NaN,0.08996,NaN,0.0000,0.0000,0.2871,0.07039,1

#Using column Transformer

In [198]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [199]:
numerical =df.select_dtypes(include=['int64', 'float64']).columns
categorical = df.select_dtypes(include=['object', 'category']).columns
numerical

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'smoothness error',
       'compactness error', 'concavity error', 'concave points error',
       'symmetry error', 'fractal dimension error', 'worst radius',
       'worst texture', 'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension', 'target'],
      dtype='object')

In [200]:
categorical

Index(['area error'], dtype='object')

In [201]:
cleaner = ColumnTransformer(
    transformers=[
        ('numerical_transformer', SimpleImputer(strategy='mean'), numerical),
        ('categorical_transformer', SimpleImputer(strategy='most_frequent'), categorical)
        ])

In [209]:
df6 = pd.DataFrame(cleaner.fit_transform(df), columns=numerical.tolist() + categorical.tolist())
df6

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target,area error
0,14.059548,10.38,122.8,1001.0,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,...,107.322848,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189,0.0,A
1,20.57,17.77,132.9,1326.0,0.097156,0.104531,0.0869,0.07017,0.181405,0.05667,...,158.8,1956.0,0.1238,0.1866,0.2416,0.186,0.275,0.084363,0.0,A
2,19.69,21.25,130.0,1203.0,0.1096,0.1599,0.094063,0.049115,0.181405,0.05999,...,107.322848,1709.0,0.1444,0.4245,0.4504,0.243,0.3613,0.08758,0.0,A
3,11.42,20.38,77.58,386.1,0.1425,0.2839,0.2414,0.049115,0.2597,0.09744,...,107.322848,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.173,0.0,A
4,20.29,14.34,92.039025,661.522581,0.097156,0.1328,0.198,0.049115,0.1809,0.062626,...,152.2,1575.0,0.1374,0.256748,0.4,0.1625,0.2364,0.07678,0.0,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.0,1479.0,0.111,0.104531,0.2439,0.1389,0.1726,0.05623,...,166.1,2027.0,0.141,0.2113,0.4107,0.2216,0.206,0.07115,0.0,A
565,14.059548,28.25,131.2,1261.0,0.0978,0.1034,0.144,0.09791,0.1752,0.062626,...,155.0,1731.0,0.1166,0.1922,0.3215,0.1628,0.2572,0.084363,0.0,A
566,16.6,28.08,108.3,661.522581,0.08455,0.1023,0.094063,0.05302,0.159,0.05648,...,126.7,1124.0,0.1139,0.256748,0.3403,0.1418,0.2218,0.0782,0.0,A
567,20.6,29.33,140.1,1265.0,0.1178,0.277,0.3514,0.152,0.2397,0.062626,...,184.6,1821.0,0.165,0.8681,0.9387,0.265,0.4087,0.124,0.0,A
568,7.76,19.311829,47.92,181.0,0.05263,0.04362,0.0,0.0,0.1587,0.05884,...,59.16,893.873828,0.08996,0.256748,0.0,0.0,0.2871,0.07039,1.0,A

In [212]:
cleaner = ColumnTransformer(
    transformers=[
        ('numerical_transformer', SimpleImputer(strategy='mean'), [0,1,2]),
        ('categorical_transformer', SimpleImputer(strategy='most_frequent'), categorical)
        ],remainder='passthrough')
df7 = pd.DataFrame(cleaner.fit_transform(df), columns=numerical.tolist() + categorical.tolist())
df7

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target,area error
0,14.059548,10.38,122.8,A,1001.0,0.1184,0.2776,0.3001,0.1471,0.2419,...,17.33,NaN,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189,0.0
1,20.57,17.77,132.9,A,1326.0,NaN,NaN,0.0869,0.07017,NaN,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.186,0.275,NaN,0.0
2,19.69,21.25,130.0,A,1203.0,0.1096,0.1599,NaN,NaN,NaN,...,25.53,NaN,1709.0,0.1444,0.4245,0.4504,0.243,0.3613,0.08758,0.0
3,11.42,20.38,77.58,A,386.1,0.1425,0.2839,0.2414,NaN,0.2597,...,26.5,NaN,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.173,0.0
4,20.29,14.34,92.039025,A,NaN,NaN,0.1328,0.198,NaN,0.1809,...,16.67,152.2,1575.0,0.1374,NaN,0.4,0.1625,0.2364,0.07678,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.0,A,1479.0,0.111,NaN,0.2439,0.1389,0.1726,...,26.4,166.1,2027.0,0.141,0.2113,0.4107,0.2216,0.206,0.07115,0.0
565,14.059548,28.25,131.2,A,1261.0,0.0978,0.1034,0.144,0.09791,0.1752,...,38.25,155.0,1731.0,0.1166,0.1922,0.3215,0.1628,0.2572,NaN,0.0
566,16.6,28.08,108.3,A,NaN,0.08455,0.1023,NaN,0.05302,0.159,...,34.12,126.7,1124.0,0.1139,NaN,0.3403,0.1418,0.2218,0.0782,0.0
567,20.6,29.33,140.1,A,1265.0,0.1178,0.277,0.3514,0.152,0.2397,...,NaN,184.6,1821.0,0.165,0.8681,0.9387,0.265,0.4087,0.124,0.0
568,7.76,19.311829,47.92,A,181.0,0.05263,0.04362,0.0,0.0,0.1587,...,30.37,59.16,NaN,0.08996,NaN,0.0,0.0,0.2871,0.07039,1.0

In [213]:
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,NaN,2019.0,0.16220,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,NaN,NaN,0.0869,0.07017,NaN,0.05667,...,23.41,158.80,1956.0,0.12380,0.1866,0.2416,0.1860,0.2750,NaN,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,NaN,NaN,NaN,0.05999,...,25.53,NaN,1709.0,0.14440,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,NaN,0.2597,0.09744,...,26.50,NaN,567.7,0.20980,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,NaN,NaN,NaN,0.13280,0.1980,NaN,0.1809,NaN,...,16.67,152.20,1575.0,0.13740,NaN,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,NaN,0.2439,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.2113,0.4107,0.2216,0.2060,0.07115,0
565,NaN,28.25,131.20,1261.0,0.09780,0.10340,0.1440,0.09791,0.1752,NaN,...,38.25,155.00,1731.0,0.11660,0.1922,0.3215,0.1628,0.2572,NaN,0
566,16.60,28.08,108.30,NaN,0.08455,0.10230,NaN,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,NaN,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.15200,0.2397,NaN,...,NaN,184.60,1821.0,0.16500,0.8681,0.9387,0.2650,0.4087,0.12400,0
568,7.76,NaN,47.92,181.0,0.05263,0.04362,0.0000,0.00000,0.1587,0.05884,...,30.37,59.16,NaN,0.08996,NaN,0.0000,0.0000,0.2871,0.07039,1

Make column_selector

In [221]:
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.impute import SimpleImputer

cleaner = ColumnTransformer(
    transformers=[
        ('numerical_transformer', SimpleImputer(strategy='mean'),
         make_column_selector(dtype_include=['int64', 'float64'])),
        ('categorical_transformer', SimpleImputer(strategy='most_frequent'),
         make_column_selector(dtype_include=['object', 'category']))
    ],
    remainder='drop'
)
df8 = pd.DataFrame(cleaner.fit_transform(df), columns=numerical.tolist() + categorical.tolist())
df8

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target,area error
0,14.059548,10.38,122.8,1001.0,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,...,107.322848,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189,0.0,A
1,20.57,17.77,132.9,1326.0,0.097156,0.104531,0.0869,0.07017,0.181405,0.05667,...,158.8,1956.0,0.1238,0.1866,0.2416,0.186,0.275,0.084363,0.0,A
2,19.69,21.25,130.0,1203.0,0.1096,0.1599,0.094063,0.049115,0.181405,0.05999,...,107.322848,1709.0,0.1444,0.4245,0.4504,0.243,0.3613,0.08758,0.0,A
3,11.42,20.38,77.58,386.1,0.1425,0.2839,0.2414,0.049115,0.2597,0.09744,...,107.322848,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.173,0.0,A
4,20.29,14.34,92.039025,661.522581,0.097156,0.1328,0.198,0.049115,0.1809,0.062626,...,152.2,1575.0,0.1374,0.256748,0.4,0.1625,0.2364,0.07678,0.0,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.0,1479.0,0.111,0.104531,0.2439,0.1389,0.1726,0.05623,...,166.1,2027.0,0.141,0.2113,0.4107,0.2216,0.206,0.07115,0.0,A
565,14.059548,28.25,131.2,1261.0,0.0978,0.1034,0.144,0.09791,0.1752,0.062626,...,155.0,1731.0,0.1166,0.1922,0.3215,0.1628,0.2572,0.084363,0.0,A
566,16.6,28.08,108.3,661.522581,0.08455,0.1023,0.094063,0.05302,0.159,0.05648,...,126.7,1124.0,0.1139,0.256748,0.3403,0.1418,0.2218,0.0782,0.0,A
567,20.6,29.33,140.1,1265.0,0.1178,0.277,0.3514,0.152,0.2397,0.062626,...,184.6,1821.0,0.165,0.8681,0.9387,0.265,0.4087,0.124,0.0,A
568,7.76,19.311829,47.92,181.0,0.05263,0.04362,0.0,0.0,0.1587,0.05884,...,59.16,893.873828,0.08996,0.256748,0.0,0.0,0.2871,0.07039,1.0,A