# Feature selection using F- classifire and Mutual_info_classifier

In [70]:
import pandas as pd

In [71]:
from sklearn.feature_selection import SelectKBest, f_classif, mutual_info_classif

In [72]:
df = pd.read_csv('sample_dataset.csv')
df.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension',
       'target'],
      dtype='object')

In [73]:
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,NaN,2019.0,0.16220,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,NaN,NaN,0.0869,0.07017,NaN,0.05667,...,23.41,158.80,1956.0,0.12380,0.1866,0.2416,0.1860,0.2750,NaN,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,NaN,NaN,NaN,0.05999,...,25.53,NaN,1709.0,0.14440,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,NaN,0.2597,0.09744,...,26.50,NaN,567.7,0.20980,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,NaN,NaN,NaN,0.13280,0.1980,NaN,0.1809,NaN,...,16.67,152.20,1575.0,0.13740,NaN,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,NaN,0.2439,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.2113,0.4107,0.2216,0.2060,0.07115,0
565,NaN,28.25,131.20,1261.0,0.09780,0.10340,0.1440,0.09791,0.1752,NaN,...,38.25,155.00,1731.0,0.11660,0.1922,0.3215,0.1628,0.2572,NaN,0
566,16.60,28.08,108.30,NaN,0.08455,0.10230,NaN,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,NaN,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.15200,0.2397,NaN,...,NaN,184.60,1821.0,0.16500,0.8681,0.9387,0.2650,0.4087,0.12400,0
568,7.76,NaN,47.92,181.0,0.05263,0.04362,0.0000,0.00000,0.1587,0.05884,...,30.37,59.16,NaN,0.08996,NaN,0.0000,0.0000,0.2871,0.07039,1

In [74]:
print(df.columns.tolist())

['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension', 'radius error', 'texture error', 'perimeter error', 'area error', 'smoothness error', 'compactness error', 'concavity error', 'concave points error', 'symmetry error', 'fractal dimension error', 'worst radius', 'worst texture', 'worst perimeter', 'worst area', 'worst smoothness', 'worst compactness', 'worst concavity', 'worst concave points', 'worst symmetry', 'worst fractal dimension', 'target']

In [75]:
df = df.loc[: ,['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'target']].dropna()

In [76]:
x = df.iloc[: , 0:10]
y = df['target']
y

8      0
18     0
20     1
21     1
39     0
43     0
58     1
63     1
64     0
73     0
105    0
128    1
134    0
146    0
158    1
166    1
185    1
205    0
213    0
239    0
251    1
253    0
277    0
281    1
294    1
296    1
300    0
301    1
326    1
334    1
336    1
351    0
374    1
377    1
390    1
393    0
396    1
405    1
427    1
430    0
446    0
455    1
460    0
468    0
485    1
493    1
510    1
511    1
512    0
526    1
535    0
560    1
Name: target, dtype: int64

In [77]:
selector = SelectKBest(f_classif, k= 5)
selector.fit(x,y)

SelectKBest(k=5)

In [78]:
selector.transform(x)

array([[1.300e+01, 8.750e+01, 5.198e+02, 1.859e-01, 9.353e-02],
       [1.981e+01, 1.300e+02, 1.260e+03, 1.479e-01, 9.498e-02],
       [1.308e+01, 8.563e+01, 5.200e+02, 4.568e-02, 3.110e-02],
       [9.504e+00, 6.034e+01, 2.739e+02, 2.956e-02, 2.076e-02],
       [1.348e+01, 8.840e+01, 5.592e+02, 1.063e-01, 5.439e-02],
       [1.328e+01, 8.732e+01, 5.452e+02, 9.847e-02, 6.158e-02],
       [1.305e+01, 8.261e+01, 5.272e+02, 6.920e-04, 4.167e-03],
       [9.173e+00, 5.920e+01, 2.609e+02, 5.988e-02, 2.180e-02],
       [1.268e+01, 8.269e+01, 4.990e+02, 1.128e-01, 6.873e-02],
       [1.380e+01, 9.043e+01, 5.841e+02, 7.789e-02, 5.069e-02],
       [1.311e+01, 8.721e+01, 5.302e+02, 2.071e-01, 9.601e-02],
       [1.510e+01, 9.958e+01, 6.745e+02, 1.138e-01, 8.534e-02],
       [1.845e+01, 1.202e+02, 1.075e+03, 1.153e-01, 6.847e-02],
       [1.180e+01, 7.899e+01, 4.320e+02, 1.659e-01, 7.415e-02],
       [1.206e+01, 7.684e+01, 4.486e+02, 1.972e-02, 1.963e-02],
       [1.080e+01, 6.877e+01, 3.576e+02, 2.531e-02, 1.698e-02],
       [1.008e+01, 6.376e+01, 3.175e+02, 1.597e-03, 2.404e-03],
       [1.512e+01, 9.878e+01, 7.166e+02, 7.550e-02, 4.079e-02],
       [1.742e+01, 1.145e+02, 9.480e+02, 1.682e-01, 6.597e-02],
       [1.746e+01, 1.134e+02, 9.206e+02, 1.417e-01, 8.811e-02],
       [1.150e+01, 7.328e+01, 4.074e+02, 2.638e-02, 2.069e-02],
       [1.730e+01, 1.130e+02, 9.282e+02, 1.266e-01, 8.353e-02],
       [1.881e+01, 1.209e+02, 1.102e+03, 8.020e-02, 5.843e-02],
       [1.174e+01, 7.424e+01, 4.273e+02, 2.245e-02, 2.763e-02],
       [1.272e+01, 8.178e+01, 4.921e+02, 1.288e-02, 1.924e-02],
       [1.091e+01, 6.914e+01, 3.637e+02, 1.236e-02, 1.369e-02],
       [1.953e+01, 1.295e+02, 1.217e+03, 2.197e-01, 1.062e-01],
       [1.246e+01, 8.043e+01, 4.713e+02, 6.830e-02, 3.099e-02],
       [1.411e+01, 9.003e+01, 6.165e+02, 1.765e-02, 2.733e-02],
       [1.230e+01, 7.788e+01, 4.644e+02, 7.756e-03, 8.535e-03],
       [1.299e+01, 8.408e+01, 5.143e+02, 3.738e-02, 2.098e-02],
       [1.575e+01, 1.071e+02, 7.586e+02, 2.914e-01, 1.242e-01],
       [1.369e+01, 8.784e+01, 5.791e+02, 2.556e-02, 2.031e-02],
       [1.346e+01, 8.589e+01, 5.621e+02, 1.271e-02, 1.117e-02],
       [1.026e+01, 6.575e+01, 3.216e+02, 1.923e-02, 1.968e-02],
       [2.161e+01, 1.444e+02, 1.407e+03, 2.810e-01, 1.562e-01],
       [1.351e+01, 8.810e+01, 5.581e+02, 8.580e-02, 5.381e-02],
       [1.094e+01, 7.039e+01, 3.700e+02, 4.944e-02, 2.932e-02],
       [1.080e+01, 6.879e+01, 3.599e+02, 3.614e-02, 1.404e-02],
       [1.490e+01, 1.021e+02, 6.850e+02, 2.733e-01, 9.711e-02],
       [1.775e+01, 1.173e+02, 9.816e+02, 1.698e-01, 8.293e-02],
       [1.338e+01, 8.634e+01, 5.572e+02, 2.819e-02, 3.264e-02],
       [1.708e+01, 1.112e+02, 9.309e+02, 1.007e-01, 6.431e-02],
       [1.760e+01, 1.190e+02, 9.805e+02, 2.136e-01, 1.002e-01],
       [1.245e+01, 8.285e+01, 4.767e+02, 1.544e-01, 4.846e-02],
       [1.246e+01, 7.883e+01, 4.773e+02, 7.173e-03, 1.149e-02],
       [1.174e+01, 7.631e+01, 4.260e+02, 6.726e-02, 2.639e-02],
       [1.481e+01, 9.466e+01, 6.807e+02, 3.416e-02, 2.541e-02],
       [1.340e+01, 8.864e+01, 5.567e+02, 1.445e-01, 8.172e-02],
       [1.346e+01, 8.744e+01, 5.511e+02, 4.201e-02, 3.152e-02],
       [2.055e+01, 1.378e+02, 1.308e+03, 2.085e-01, 1.322e-01],
       [1.405e+01, 9.138e+01, 6.004e+02, 4.462e-02, 4.304e-02]])

In [79]:
get_featured = x.columns[selector.get_support()]
get_featured

Index(['mean radius', 'mean perimeter', 'mean area', 'mean concavity',
       'mean concave points'],
      dtype='object')

## feature selection using mutual_info_classifier

In [80]:
selector = SelectKBest(mutual_info_classif, k= 5)
selector.fit(x,y)

SelectKBest(k=5,
            score_func=<function mutual_info_classif at 0x0000027BDB1B2A20>)

In [81]:
selector.transform(x)

array([[1.300e+01, 8.750e+01, 5.198e+02, 1.859e-01, 9.353e-02],
       [1.981e+01, 1.300e+02, 1.260e+03, 1.479e-01, 9.498e-02],
       [1.308e+01, 8.563e+01, 5.200e+02, 4.568e-02, 3.110e-02],
       [9.504e+00, 6.034e+01, 2.739e+02, 2.956e-02, 2.076e-02],
       [1.348e+01, 8.840e+01, 5.592e+02, 1.063e-01, 5.439e-02],
       [1.328e+01, 8.732e+01, 5.452e+02, 9.847e-02, 6.158e-02],
       [1.305e+01, 8.261e+01, 5.272e+02, 6.920e-04, 4.167e-03],
       [9.173e+00, 5.920e+01, 2.609e+02, 5.988e-02, 2.180e-02],
       [1.268e+01, 8.269e+01, 4.990e+02, 1.128e-01, 6.873e-02],
       [1.380e+01, 9.043e+01, 5.841e+02, 7.789e-02, 5.069e-02],
       [1.311e+01, 8.721e+01, 5.302e+02, 2.071e-01, 9.601e-02],
       [1.510e+01, 9.958e+01, 6.745e+02, 1.138e-01, 8.534e-02],
       [1.845e+01, 1.202e+02, 1.075e+03, 1.153e-01, 6.847e-02],
       [1.180e+01, 7.899e+01, 4.320e+02, 1.659e-01, 7.415e-02],
       [1.206e+01, 7.684e+01, 4.486e+02, 1.972e-02, 1.963e-02],
       [1.080e+01, 6.877e+01, 3.576e+02, 2.531e-02, 1.698e-02],
       [1.008e+01, 6.376e+01, 3.175e+02, 1.597e-03, 2.404e-03],
       [1.512e+01, 9.878e+01, 7.166e+02, 7.550e-02, 4.079e-02],
       [1.742e+01, 1.145e+02, 9.480e+02, 1.682e-01, 6.597e-02],
       [1.746e+01, 1.134e+02, 9.206e+02, 1.417e-01, 8.811e-02],
       [1.150e+01, 7.328e+01, 4.074e+02, 2.638e-02, 2.069e-02],
       [1.730e+01, 1.130e+02, 9.282e+02, 1.266e-01, 8.353e-02],
       [1.881e+01, 1.209e+02, 1.102e+03, 8.020e-02, 5.843e-02],
       [1.174e+01, 7.424e+01, 4.273e+02, 2.245e-02, 2.763e-02],
       [1.272e+01, 8.178e+01, 4.921e+02, 1.288e-02, 1.924e-02],
       [1.091e+01, 6.914e+01, 3.637e+02, 1.236e-02, 1.369e-02],
       [1.953e+01, 1.295e+02, 1.217e+03, 2.197e-01, 1.062e-01],
       [1.246e+01, 8.043e+01, 4.713e+02, 6.830e-02, 3.099e-02],
       [1.411e+01, 9.003e+01, 6.165e+02, 1.765e-02, 2.733e-02],
       [1.230e+01, 7.788e+01, 4.644e+02, 7.756e-03, 8.535e-03],
       [1.299e+01, 8.408e+01, 5.143e+02, 3.738e-02, 2.098e-02],
       [1.575e+01, 1.071e+02, 7.586e+02, 2.914e-01, 1.242e-01],
       [1.369e+01, 8.784e+01, 5.791e+02, 2.556e-02, 2.031e-02],
       [1.346e+01, 8.589e+01, 5.621e+02, 1.271e-02, 1.117e-02],
       [1.026e+01, 6.575e+01, 3.216e+02, 1.923e-02, 1.968e-02],
       [2.161e+01, 1.444e+02, 1.407e+03, 2.810e-01, 1.562e-01],
       [1.351e+01, 8.810e+01, 5.581e+02, 8.580e-02, 5.381e-02],
       [1.094e+01, 7.039e+01, 3.700e+02, 4.944e-02, 2.932e-02],
       [1.080e+01, 6.879e+01, 3.599e+02, 3.614e-02, 1.404e-02],
       [1.490e+01, 1.021e+02, 6.850e+02, 2.733e-01, 9.711e-02],
       [1.775e+01, 1.173e+02, 9.816e+02, 1.698e-01, 8.293e-02],
       [1.338e+01, 8.634e+01, 5.572e+02, 2.819e-02, 3.264e-02],
       [1.708e+01, 1.112e+02, 9.309e+02, 1.007e-01, 6.431e-02],
       [1.760e+01, 1.190e+02, 9.805e+02, 2.136e-01, 1.002e-01],
       [1.245e+01, 8.285e+01, 4.767e+02, 1.544e-01, 4.846e-02],
       [1.246e+01, 7.883e+01, 4.773e+02, 7.173e-03, 1.149e-02],
       [1.174e+01, 7.631e+01, 4.260e+02, 6.726e-02, 2.639e-02],
       [1.481e+01, 9.466e+01, 6.807e+02, 3.416e-02, 2.541e-02],
       [1.340e+01, 8.864e+01, 5.567e+02, 1.445e-01, 8.172e-02],
       [1.346e+01, 8.744e+01, 5.511e+02, 4.201e-02, 3.152e-02],
       [2.055e+01, 1.378e+02, 1.308e+03, 2.085e-01, 1.322e-01],
       [1.405e+01, 9.138e+01, 6.004e+02, 4.462e-02, 4.304e-02]])

In [82]:
get_featured = x.columns[selector.get_support()]
get_featured

Index(['mean radius', 'mean perimeter', 'mean area', 'mean concavity',
       'mean concave points'],
      dtype='object')

### categorical feature and numerical target

In [83]:
import pandas as pd
from sklearn.feature_selection import SelectKBest, mutual_info_regression
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder

In [84]:
df = pd.read_csv("sample_dataset_bins.csv")
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error
0,"(11.207, 13.32]","(21.538, 24.495]","(87.203, 101.674]","(379.25, 615.0]","(0.119, 0.13]","(0.182, 0.215]","(0.171, 0.213]","(0.0805, 0.101]","(0.217, 0.235]","(0.0737, 0.0784]",0.3063
1,"(19.658, 21.771]","(21.538, 24.495]","(116.145, 130.616]","(1086.5, 1322.25]","(0.0969, 0.108]","(0.0846, 0.117]","(0.128, 0.171]","(0.0805, 0.101]","(0.143, 0.161]","(0.0499, 0.0547]",0.7582
2,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0642, 0.069]",0.1852
3,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.069, 0.0737]",0.2773
4,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0854, 0.128]","(0.0402, 0.0604]","(0.161, 0.18]","(0.0595, 0.0642]",0.2130
5,"(11.207, 13.32]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.18, 0.198]","(0.0642, 0.069]",0.3704
6,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.18, 0.198]","(0.0547, 0.0595]",0.4040
7,"(9.094, 11.207]","(12.667, 15.624]","(58.261, 72.732]","(141.142, 379.25]","(0.0748, 0.0859]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.217, 0.235]","(0.069, 0.0737]",0.4098
8,"(11.207, 13.32]","(21.538, 24.495]","(72.732, 87.203]","(379.25, 615.0]","(0.108, 0.119]","(0.117, 0.15]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.18, 0.198]","(0.0642, 0.069]",0.4255
9,"(11.207, 13.32]","(12.667, 15.624]","(87.203, 101.674]","(379.25, 615.0]","(0.13, 0.141]","(0.15, 0.182]","(0.171, 0.213]","(0.0805, 0.101]","(0.18, 0.198]","(0.0737, 0.0784]",0.3908
10,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(615.0, 850.75]","(0.108, 0.119]","(0.15, 0.182]","(0.0854, 0.128]","(0.0805, 0.101]","(0.198, 0.217]","(0.0642, 0.069]",0.4309
11,"(17.545, 19.658]","(21.538, 24.495]","(116.145, 130.616]","(850.75, 1086.5]","(0.0859, 0.0969]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.161, 0.18]","(0.0547, 0.0595]",0.5959
12,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.108, 0.119]","(0.15, 0.182]","(0.128, 0.171]","(0.0604, 0.0805]","(0.254, 0.272]","(0.0737, 0.0784]",0.3197
13,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0547, 0.0595]",0.1822
14,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.124, 0.143]","(0.0595, 0.0642]",0.1728
15,"(9.094, 11.207]","(12.667, 15.624]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.161, 0.18]","(0.0595, 0.0642]",0.4245
16,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(615.0, 850.75]","(0.0859, 0.0969]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0595, 0.0642]",0.2711
17,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0547, 0.0595]",0.3927
18,"(15.433, 17.545]","(15.624, 18.581]","(101.674, 116.145]","(850.75, 1086.5]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0805, 0.101]","(0.18, 0.198]","(0.0547, 0.0595]",0.3093
19,"(17.545, 19.658]","(18.581, 21.538]","(116.145, 130.616]","(1086.5, 1322.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0499, 0.0547]",0.3283
20,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.198, 0.217]","(0.0595, 0.0642]",0.5619
21,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0595, 0.0642]",0.1753
22,"(17.545, 19.658]","(18.581, 21.538]","(116.145, 130.616]","(1086.5, 1322.25]","(0.108, 0.119]","(0.15, 0.182]","(0.213, 0.256]","(0.101, 0.121]","(0.161, 0.18]","(0.0642, 0.069]",1.1110
23,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0595, 0.0642]",0.3642
24,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0547, 0.0595]",0.1840
25,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.0846, 0.117]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.069, 0.0737]",0.1814
26,"(15.433, 17.545]","(18.581, 21.538]","(101.674, 116.145]","(615.0, 850.75]","(0.119, 0.13]","(0.215, 0.248]","(0.256, 0.299]","(0.121, 0.141]","(0.235, 0.254]","(0.0737, 0.0784]",0.5204
27,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(379.25, 615.0]","(0.0748, 0.0859]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0547, 0.0595]",0.1705
28,"(13.32, 15.433]","(27.452, 30.409]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.124, 0.143]","(0.0547, 0.0595]",0.1689
29,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.18, 0.198]","(0.0642, 0.069]",0.1911
30,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0402, 0.0604]","(0.18, 0.198]","(0.0595, 0.0642]",0.2136
31,"(9.094, 11.207]","(18.581, 21.538]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.143, 0.161]","(0.0642, 0.069]",0.3796
32,"(9.094, 11.207]","(21.538, 24.495]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.198, 0.217]","(0.0595, 0.0642]",0.3077
33,"(13.32, 15.433]","(21.538, 24.495]","(101.674, 116.145]","(615.0, 850.75]","(0.0969, 0.108]","(0.215, 0.248]","(0.256, 0.299]","(0.0805, 0.101]","(0.198, 0.217]","(0.069, 0.0737]",0.2530
34,"(17.545, 19.658]","(27.452, 30.409]","(116.145, 130.616]","(850.75, 1086.5]","(0.0969, 0.108]","(0.117, 0.15]","(0.128, 0.171]","(0.0805, 0.101]","(0.161, 0.18]","(0.0547, 0.0595]",0.3897
35,"(13.32, 15.433]","(30.409, 33.366]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.124, 0.143]","(0.0595, 0.0642]",0.3408
36,"(17.545, 19.658]","(21.538, 24.495]","(116.145, 130.616]","(850.75, 1086.5]","(0.0859, 0.0969]","(0.182, 0.215]","(0.213, 0.256]","(0.0805, 0.101]","(0.161, 0.18]","(0.069, 0.0737]",0.9289
37,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.15, 0.182]","(0.128, 0.171]","(0.0402, 0.0604]","(0.198, 0.217]","(0.069, 0.0737]",0.3921
38,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0637, 0.0748]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0595, 0.0642]",0.3276
39,"(13.32, 15.433]","(12.667, 15.624]","(87.203, 101.674]","(615.0, 850.75]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0499, 0.0547]",0.2182
40,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.108, 0.119]","(0.117, 0.15]","(0.128, 0.171]","(0.0805, 0.101]","(0.198, 0.217]","(0.069, 0.0737]",0.3906
41,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0595, 0.0642]",0.1998
42,"(19.658, 21.771]","(18.581, 21.538]","(130.616, 145.087]","(1086.5, 1322.25]","(0.0969, 0.108]","(0.15, 0.182]","(0.171, 0.213]","(0.121, 0.141]","(0.198, 0.217]","(0.0595, 0.0642]",0.6986
43,"(13.32, 15.433]","(24.495, 27.452]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0595, 0.0642]",0.3645

In [85]:
df['radius error'] = pd.cut(df['radius error'], 10)

In [86]:
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error
0,"(11.207, 13.32]","(21.538, 24.495]","(87.203, 101.674]","(379.25, 615.0]","(0.119, 0.13]","(0.182, 0.215]","(0.171, 0.213]","(0.0805, 0.101]","(0.217, 0.235]","(0.0737, 0.0784]","(0.263, 0.357]"
1,"(19.658, 21.771]","(21.538, 24.495]","(116.145, 130.616]","(1086.5, 1322.25]","(0.0969, 0.108]","(0.0846, 0.117]","(0.128, 0.171]","(0.0805, 0.101]","(0.143, 0.161]","(0.0499, 0.0547]","(0.734, 0.828]"
2,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0642, 0.069]","(0.168, 0.263]"
3,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.069, 0.0737]","(0.263, 0.357]"
4,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0854, 0.128]","(0.0402, 0.0604]","(0.161, 0.18]","(0.0595, 0.0642]","(0.168, 0.263]"
5,"(11.207, 13.32]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.18, 0.198]","(0.0642, 0.069]","(0.357, 0.452]"
6,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.18, 0.198]","(0.0547, 0.0595]","(0.357, 0.452]"
7,"(9.094, 11.207]","(12.667, 15.624]","(58.261, 72.732]","(141.142, 379.25]","(0.0748, 0.0859]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.217, 0.235]","(0.069, 0.0737]","(0.357, 0.452]"
8,"(11.207, 13.32]","(21.538, 24.495]","(72.732, 87.203]","(379.25, 615.0]","(0.108, 0.119]","(0.117, 0.15]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.18, 0.198]","(0.0642, 0.069]","(0.357, 0.452]"
9,"(11.207, 13.32]","(12.667, 15.624]","(87.203, 101.674]","(379.25, 615.0]","(0.13, 0.141]","(0.15, 0.182]","(0.171, 0.213]","(0.0805, 0.101]","(0.18, 0.198]","(0.0737, 0.0784]","(0.357, 0.452]"
10,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(615.0, 850.75]","(0.108, 0.119]","(0.15, 0.182]","(0.0854, 0.128]","(0.0805, 0.101]","(0.198, 0.217]","(0.0642, 0.069]","(0.357, 0.452]"
11,"(17.545, 19.658]","(21.538, 24.495]","(116.145, 130.616]","(850.75, 1086.5]","(0.0859, 0.0969]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.161, 0.18]","(0.0547, 0.0595]","(0.546, 0.64]"
12,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.108, 0.119]","(0.15, 0.182]","(0.128, 0.171]","(0.0604, 0.0805]","(0.254, 0.272]","(0.0737, 0.0784]","(0.263, 0.357]"
13,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0547, 0.0595]","(0.168, 0.263]"
14,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.124, 0.143]","(0.0595, 0.0642]","(0.168, 0.263]"
15,"(9.094, 11.207]","(12.667, 15.624]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.161, 0.18]","(0.0595, 0.0642]","(0.357, 0.452]"
16,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(615.0, 850.75]","(0.0859, 0.0969]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0595, 0.0642]","(0.263, 0.357]"
17,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0547, 0.0595]","(0.357, 0.452]"
18,"(15.433, 17.545]","(15.624, 18.581]","(101.674, 116.145]","(850.75, 1086.5]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0805, 0.101]","(0.18, 0.198]","(0.0547, 0.0595]","(0.263, 0.357]"
19,"(17.545, 19.658]","(18.581, 21.538]","(116.145, 130.616]","(1086.5, 1322.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0499, 0.0547]","(0.263, 0.357]"
20,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.198, 0.217]","(0.0595, 0.0642]","(0.546, 0.64]"
21,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0595, 0.0642]","(0.168, 0.263]"
22,"(17.545, 19.658]","(18.581, 21.538]","(116.145, 130.616]","(1086.5, 1322.25]","(0.108, 0.119]","(0.15, 0.182]","(0.213, 0.256]","(0.101, 0.121]","(0.161, 0.18]","(0.0642, 0.069]","(1.017, 1.111]"
23,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0595, 0.0642]","(0.357, 0.452]"
24,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0547, 0.0595]","(0.168, 0.263]"
25,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.0846, 0.117]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.069, 0.0737]","(0.168, 0.263]"
26,"(15.433, 17.545]","(18.581, 21.538]","(101.674, 116.145]","(615.0, 850.75]","(0.119, 0.13]","(0.215, 0.248]","(0.256, 0.299]","(0.121, 0.141]","(0.235, 0.254]","(0.0737, 0.0784]","(0.452, 0.546]"
27,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(379.25, 615.0]","(0.0748, 0.0859]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0547, 0.0595]","(0.168, 0.263]"
28,"(13.32, 15.433]","(27.452, 30.409]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.124, 0.143]","(0.0547, 0.0595]","(0.168, 0.263]"
29,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.18, 0.198]","(0.0642, 0.069]","(0.168, 0.263]"
30,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0402, 0.0604]","(0.18, 0.198]","(0.0595, 0.0642]","(0.168, 0.263]"
31,"(9.094, 11.207]","(18.581, 21.538]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.143, 0.161]","(0.0642, 0.069]","(0.357, 0.452]"
32,"(9.094, 11.207]","(21.538, 24.495]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.198, 0.217]","(0.0595, 0.0642]","(0.263, 0.357]"
33,"(13.32, 15.433]","(21.538, 24.495]","(101.674, 116.145]","(615.0, 850.75]","(0.0969, 0.108]","(0.215, 0.248]","(0.256, 0.299]","(0.0805, 0.101]","(0.198, 0.217]","(0.069, 0.0737]","(0.168, 0.263]"
34,"(17.545, 19.658]","(27.452, 30.409]","(116.145, 130.616]","(850.75, 1086.5]","(0.0969, 0.108]","(0.117, 0.15]","(0.128, 0.171]","(0.0805, 0.101]","(0.161, 0.18]","(0.0547, 0.0595]","(0.357, 0.452]"
35,"(13.32, 15.433]","(30.409, 33.366]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.124, 0.143]","(0.0595, 0.0642]","(0.263, 0.357]"
36,"(17.545, 19.658]","(21.538, 24.495]","(116.145, 130.616]","(850.75, 1086.5]","(0.0859, 0.0969]","(0.182, 0.215]","(0.213, 0.256]","(0.0805, 0.101]","(0.161, 0.18]","(0.069, 0.0737]","(0.923, 1.017]"
37,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.15, 0.182]","(0.128, 0.171]","(0.0402, 0.0604]","(0.198, 0.217]","(0.069, 0.0737]","(0.357, 0.452]"
38,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0637, 0.0748]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0595, 0.0642]","(0.263, 0.357]"
39,"(13.32, 15.433]","(12.667, 15.624]","(87.203, 101.674]","(615.0, 850.75]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0499, 0.0547]","(0.168, 0.263]"
40,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.108, 0.119]","(0.117, 0.15]","(0.128, 0.171]","(0.0805, 0.101]","(0.198, 0.217]","(0.069, 0.0737]","(0.357, 0.452]"
41,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0595, 0.0642]","(0.168, 0.263]"
42,"(19.658, 21.771]","(18.581, 21.538]","(130.616, 145.087]","(1086.5, 1322.25]","(0.0969, 0.108]","(0.15, 0.182]","(0.171, 0.213]","(0.121, 0.141]","(0.198, 0.217]","(0.0595, 0.0642]","(0.64, 0.734]"
43,"(13.32, 15.433]","(24.495, 27.452]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0595, 0.0642]","(0.357, 0.452]"

In [87]:
x = df.iloc[: , 0:10]
y = df.iloc[:, -1]
x

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension
0,"(11.207, 13.32]","(21.538, 24.495]","(87.203, 101.674]","(379.25, 615.0]","(0.119, 0.13]","(0.182, 0.215]","(0.171, 0.213]","(0.0805, 0.101]","(0.217, 0.235]","(0.0737, 0.0784]"
1,"(19.658, 21.771]","(21.538, 24.495]","(116.145, 130.616]","(1086.5, 1322.25]","(0.0969, 0.108]","(0.0846, 0.117]","(0.128, 0.171]","(0.0805, 0.101]","(0.143, 0.161]","(0.0499, 0.0547]"
2,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0642, 0.069]"
3,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.069, 0.0737]"
4,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0854, 0.128]","(0.0402, 0.0604]","(0.161, 0.18]","(0.0595, 0.0642]"
5,"(11.207, 13.32]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.18, 0.198]","(0.0642, 0.069]"
6,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.18, 0.198]","(0.0547, 0.0595]"
7,"(9.094, 11.207]","(12.667, 15.624]","(58.261, 72.732]","(141.142, 379.25]","(0.0748, 0.0859]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.217, 0.235]","(0.069, 0.0737]"
8,"(11.207, 13.32]","(21.538, 24.495]","(72.732, 87.203]","(379.25, 615.0]","(0.108, 0.119]","(0.117, 0.15]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.18, 0.198]","(0.0642, 0.069]"
9,"(11.207, 13.32]","(12.667, 15.624]","(87.203, 101.674]","(379.25, 615.0]","(0.13, 0.141]","(0.15, 0.182]","(0.171, 0.213]","(0.0805, 0.101]","(0.18, 0.198]","(0.0737, 0.0784]"
10,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(615.0, 850.75]","(0.108, 0.119]","(0.15, 0.182]","(0.0854, 0.128]","(0.0805, 0.101]","(0.198, 0.217]","(0.0642, 0.069]"
11,"(17.545, 19.658]","(21.538, 24.495]","(116.145, 130.616]","(850.75, 1086.5]","(0.0859, 0.0969]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.161, 0.18]","(0.0547, 0.0595]"
12,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.108, 0.119]","(0.15, 0.182]","(0.128, 0.171]","(0.0604, 0.0805]","(0.254, 0.272]","(0.0737, 0.0784]"
13,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0547, 0.0595]"
14,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.124, 0.143]","(0.0595, 0.0642]"
15,"(9.094, 11.207]","(12.667, 15.624]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.161, 0.18]","(0.0595, 0.0642]"
16,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(615.0, 850.75]","(0.0859, 0.0969]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0595, 0.0642]"
17,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0547, 0.0595]"
18,"(15.433, 17.545]","(15.624, 18.581]","(101.674, 116.145]","(850.75, 1086.5]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0805, 0.101]","(0.18, 0.198]","(0.0547, 0.0595]"
19,"(17.545, 19.658]","(18.581, 21.538]","(116.145, 130.616]","(1086.5, 1322.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0499, 0.0547]"
20,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.198, 0.217]","(0.0595, 0.0642]"
21,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0595, 0.0642]"
22,"(17.545, 19.658]","(18.581, 21.538]","(116.145, 130.616]","(1086.5, 1322.25]","(0.108, 0.119]","(0.15, 0.182]","(0.213, 0.256]","(0.101, 0.121]","(0.161, 0.18]","(0.0642, 0.069]"
23,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0595, 0.0642]"
24,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0547, 0.0595]"
25,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.0846, 0.117]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.069, 0.0737]"
26,"(15.433, 17.545]","(18.581, 21.538]","(101.674, 116.145]","(615.0, 850.75]","(0.119, 0.13]","(0.215, 0.248]","(0.256, 0.299]","(0.121, 0.141]","(0.235, 0.254]","(0.0737, 0.0784]"
27,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(379.25, 615.0]","(0.0748, 0.0859]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0547, 0.0595]"
28,"(13.32, 15.433]","(27.452, 30.409]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.124, 0.143]","(0.0547, 0.0595]"
29,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.18, 0.198]","(0.0642, 0.069]"
30,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0402, 0.0604]","(0.18, 0.198]","(0.0595, 0.0642]"
31,"(9.094, 11.207]","(18.581, 21.538]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.143, 0.161]","(0.0642, 0.069]"
32,"(9.094, 11.207]","(21.538, 24.495]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.198, 0.217]","(0.0595, 0.0642]"
33,"(13.32, 15.433]","(21.538, 24.495]","(101.674, 116.145]","(615.0, 850.75]","(0.0969, 0.108]","(0.215, 0.248]","(0.256, 0.299]","(0.0805, 0.101]","(0.198, 0.217]","(0.069, 0.0737]"
34,"(17.545, 19.658]","(27.452, 30.409]","(116.145, 130.616]","(850.75, 1086.5]","(0.0969, 0.108]","(0.117, 0.15]","(0.128, 0.171]","(0.0805, 0.101]","(0.161, 0.18]","(0.0547, 0.0595]"
35,"(13.32, 15.433]","(30.409, 33.366]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.124, 0.143]","(0.0595, 0.0642]"
36,"(17.545, 19.658]","(21.538, 24.495]","(116.145, 130.616]","(850.75, 1086.5]","(0.0859, 0.0969]","(0.182, 0.215]","(0.213, 0.256]","(0.0805, 0.101]","(0.161, 0.18]","(0.069, 0.0737]"
37,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.15, 0.182]","(0.128, 0.171]","(0.0402, 0.0604]","(0.198, 0.217]","(0.069, 0.0737]"
38,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0637, 0.0748]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0595, 0.0642]"
39,"(13.32, 15.433]","(12.667, 15.624]","(87.203, 101.674]","(615.0, 850.75]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0499, 0.0547]"
40,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.108, 0.119]","(0.117, 0.15]","(0.128, 0.171]","(0.0805, 0.101]","(0.198, 0.217]","(0.069, 0.0737]"
41,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0595, 0.0642]"
42,"(19.658, 21.771]","(18.581, 21.538]","(130.616, 145.087]","(1086.5, 1322.25]","(0.0969, 0.108]","(0.15, 0.182]","(0.171, 0.213]","(0.121, 0.141]","(0.198, 0.217]","(0.0595, 0.0642]"
43,"(13.32, 15.433]","(24.495, 27.452]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0595, 0.0642]"

In [88]:
y

0     (0.263, 0.357]
1     (0.734, 0.828]
2     (0.168, 0.263]
3     (0.263, 0.357]
4     (0.168, 0.263]
5     (0.357, 0.452]
6     (0.357, 0.452]
7     (0.357, 0.452]
8     (0.357, 0.452]
9     (0.357, 0.452]
10    (0.357, 0.452]
11     (0.546, 0.64]
12    (0.263, 0.357]
13    (0.168, 0.263]
14    (0.168, 0.263]
15    (0.357, 0.452]
16    (0.263, 0.357]
17    (0.357, 0.452]
18    (0.263, 0.357]
19    (0.263, 0.357]
20     (0.546, 0.64]
21    (0.168, 0.263]
22    (1.017, 1.111]
23    (0.357, 0.452]
24    (0.168, 0.263]
25    (0.168, 0.263]
26    (0.452, 0.546]
27    (0.168, 0.263]
28    (0.168, 0.263]
29    (0.168, 0.263]
30    (0.168, 0.263]
31    (0.357, 0.452]
32    (0.263, 0.357]
33    (0.168, 0.263]
34    (0.357, 0.452]
35    (0.263, 0.357]
36    (0.923, 1.017]
37    (0.357, 0.452]
38    (0.263, 0.357]
39    (0.168, 0.263]
40    (0.357, 0.452]
41    (0.168, 0.263]
42     (0.64, 0.734]
43    (0.357, 0.452]
Name: radius error, dtype: category
Categories (10, interval[float64, right]): [(0.168, 0.263] < (0.263, 0.357] < (0.357, 0.452] < (0.452, 0.546] ... (0.734, 0.828] < (0.828, 0.923] < (0.923, 1.017] < (1.017, 1.111]]

In [89]:
x = OrdinalEncoder().fit_transform(x)
y = LabelEncoder().fit_transform(y)

In [90]:
selector  = SelectKBest(lambda x,y : mutual_info_regression(x,y, discrete_features= True), k = 5 )

In [91]:
selector.fit_transform(x,y)

array([[0., 5., 4., 4., 5.],
       [4., 1., 3., 4., 0.],
       [0., 4., 1., 1., 3.],
       [5., 3., 0., 1., 4.],
       [1., 5., 2., 2., 2.],
       [0., 5., 2., 3., 3.],
       [0., 4., 0., 0., 1.],
       [5., 3., 1., 1., 4.],
       [0., 4., 2., 3., 3.],
       [0., 5., 4., 4., 5.],
       [1., 5., 2., 4., 3.],
       [3., 1., 2., 3., 1.],
       [0., 4., 3., 3., 5.],
       [0., 4., 0., 0., 1.],
       [5., 3., 0., 0., 2.],
       [5., 3., 0., 0., 2.],
       [1., 5., 1., 2., 2.],
       [0., 4., 0., 1., 1.],
       [2., 0., 2., 4., 1.],
       [3., 1., 1., 2., 0.],
       [0., 4., 0., 1., 2.],
       [5., 3., 0., 0., 2.],
       [3., 1., 5., 5., 3.],
       [0., 4., 1., 1., 2.],
       [0., 4., 0., 0., 1.],
       [0., 4., 0., 1., 4.],
       [2., 0., 6., 6., 5.],
       [1., 5., 0., 1., 1.],
       [1., 4., 0., 0., 1.],
       [5., 3., 0., 0., 3.],
       [1., 5., 2., 2., 2.],
       [5., 3., 1., 1., 3.],
       [5., 3., 0., 0., 2.],
       [1., 0., 6., 4., 4.],
       [3., 1., 3., 4., 1.],
       [1., 4., 0., 1., 2.],
       [3., 1., 5., 4., 4.],
       [0., 4., 3., 2., 4.],
       [0., 4., 0., 0., 2.],
       [1., 5., 0., 1., 0.],
       [1., 5., 3., 4., 4.],
       [1., 5., 0., 1., 2.],
       [4., 2., 4., 6., 2.],
       [1., 5., 1., 2., 2.]])

In [92]:
x

array([[0., 3., 5., 2., 5., 5., 4., 4., 5., 5.],
       [4., 3., 1., 0., 3., 2., 3., 4., 1., 0.],
       [0., 1., 4., 2., 3., 3., 1., 1., 3., 3.],
       [5., 7., 3., 1., 3., 1., 0., 1., 3., 4.],
       [1., 2., 5., 2., 3., 3., 2., 2., 2., 2.],
       [0., 2., 5., 2., 3., 3., 2., 3., 3., 3.],
       [0., 2., 4., 2., 1., 0., 0., 0., 3., 1.],
       [5., 0., 3., 1., 1., 2., 1., 1., 5., 4.],
       [0., 3., 4., 2., 4., 3., 2., 3., 3., 3.],
       [0., 0., 5., 2., 6., 4., 4., 4., 3., 5.],
       [1., 1., 5., 3., 4., 4., 2., 4., 4., 3.],
       [3., 3., 1., 4., 2., 2., 2., 3., 2., 1.],
       [0., 1., 4., 2., 4., 4., 3., 3., 7., 5.],
       [0., 0., 4., 2., 2., 1., 0., 0., 1., 1.],
       [5., 7., 3., 1., 2., 1., 0., 0., 0., 2.],
       [5., 0., 3., 1., 2., 0., 0., 0., 2., 2.],
       [1., 1., 5., 3., 2., 2., 1., 2., 1., 2.],
       [0., 1., 4., 2., 2., 1., 0., 1., 3., 1.],
       [2., 1., 0., 4., 3., 2., 2., 4., 3., 1.],
       [3., 2., 1., 0., 2., 1., 1., 2., 1., 0.],
       [0., 0., 4., 2., 1., 0., 0., 1., 4., 2.],
       [5., 7., 3., 1., 1., 0., 0., 0., 1., 2.],
       [3., 2., 1., 0., 4., 4., 5., 5., 2., 3.],
       [0., 2., 4., 2., 1., 2., 1., 1., 2., 2.],
       [0., 2., 4., 2., 1., 0., 0., 0., 1., 1.],
       [0., 0., 4., 2., 2., 2., 0., 1., 2., 4.],
       [2., 2., 0., 3., 5., 6., 6., 6., 6., 5.],
       [1., 1., 5., 2., 1., 1., 0., 1., 3., 1.],
       [1., 5., 4., 2., 1., 0., 0., 0., 0., 1.],
       [5., 7., 3., 1., 3., 1., 0., 0., 3., 3.],
       [1., 2., 5., 2., 3., 2., 2., 2., 3., 2.],
       [5., 2., 3., 1., 3., 1., 1., 1., 1., 3.],
       [5., 3., 3., 1., 2., 1., 0., 0., 4., 2.],
       [1., 3., 0., 3., 3., 6., 6., 4., 4., 4.],
       [3., 5., 1., 4., 3., 3., 3., 4., 2., 1.],
       [1., 6., 4., 2., 2., 1., 0., 1., 0., 2.],
       [3., 3., 1., 4., 2., 5., 5., 4., 2., 4.],
       [0., 1., 4., 2., 2., 4., 3., 2., 4., 4.],
       [0., 0., 4., 2., 0., 0., 0., 0., 1., 2.],
       [1., 0., 5., 3., 1., 0., 0., 1., 2., 0.],
       [1., 2., 5., 2., 4., 3., 3., 4., 4., 4.],
       [1., 2., 5., 2., 3., 2., 0., 1., 2., 2.],
       [4., 2., 2., 0., 3., 4., 4., 6., 4., 2.],
       [1., 4., 5., 2., 3., 2., 1., 2., 1., 2.]])

### Categorocal feature - Categorocal target

In [93]:
from sklearn.feature_selection import SelectKBest,mutual_info_classif,chi2

In [94]:
df = pd.read_csv('sample_dataset_bins.csv')

In [95]:
df['radius error'] = pd.cut(df['radius error'], 10)

In [96]:
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error
0,"(11.207, 13.32]","(21.538, 24.495]","(87.203, 101.674]","(379.25, 615.0]","(0.119, 0.13]","(0.182, 0.215]","(0.171, 0.213]","(0.0805, 0.101]","(0.217, 0.235]","(0.0737, 0.0784]","(0.263, 0.357]"
1,"(19.658, 21.771]","(21.538, 24.495]","(116.145, 130.616]","(1086.5, 1322.25]","(0.0969, 0.108]","(0.0846, 0.117]","(0.128, 0.171]","(0.0805, 0.101]","(0.143, 0.161]","(0.0499, 0.0547]","(0.734, 0.828]"
2,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0642, 0.069]","(0.168, 0.263]"
3,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.069, 0.0737]","(0.263, 0.357]"
4,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0854, 0.128]","(0.0402, 0.0604]","(0.161, 0.18]","(0.0595, 0.0642]","(0.168, 0.263]"
5,"(11.207, 13.32]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.18, 0.198]","(0.0642, 0.069]","(0.357, 0.452]"
6,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.18, 0.198]","(0.0547, 0.0595]","(0.357, 0.452]"
7,"(9.094, 11.207]","(12.667, 15.624]","(58.261, 72.732]","(141.142, 379.25]","(0.0748, 0.0859]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.217, 0.235]","(0.069, 0.0737]","(0.357, 0.452]"
8,"(11.207, 13.32]","(21.538, 24.495]","(72.732, 87.203]","(379.25, 615.0]","(0.108, 0.119]","(0.117, 0.15]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.18, 0.198]","(0.0642, 0.069]","(0.357, 0.452]"
9,"(11.207, 13.32]","(12.667, 15.624]","(87.203, 101.674]","(379.25, 615.0]","(0.13, 0.141]","(0.15, 0.182]","(0.171, 0.213]","(0.0805, 0.101]","(0.18, 0.198]","(0.0737, 0.0784]","(0.357, 0.452]"
10,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(615.0, 850.75]","(0.108, 0.119]","(0.15, 0.182]","(0.0854, 0.128]","(0.0805, 0.101]","(0.198, 0.217]","(0.0642, 0.069]","(0.357, 0.452]"
11,"(17.545, 19.658]","(21.538, 24.495]","(116.145, 130.616]","(850.75, 1086.5]","(0.0859, 0.0969]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0604, 0.0805]","(0.161, 0.18]","(0.0547, 0.0595]","(0.546, 0.64]"
12,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.108, 0.119]","(0.15, 0.182]","(0.128, 0.171]","(0.0604, 0.0805]","(0.254, 0.272]","(0.0737, 0.0784]","(0.263, 0.357]"
13,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0547, 0.0595]","(0.168, 0.263]"
14,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.124, 0.143]","(0.0595, 0.0642]","(0.168, 0.263]"
15,"(9.094, 11.207]","(12.667, 15.624]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.161, 0.18]","(0.0595, 0.0642]","(0.357, 0.452]"
16,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(615.0, 850.75]","(0.0859, 0.0969]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0595, 0.0642]","(0.263, 0.357]"
17,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0547, 0.0595]","(0.357, 0.452]"
18,"(15.433, 17.545]","(15.624, 18.581]","(101.674, 116.145]","(850.75, 1086.5]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0805, 0.101]","(0.18, 0.198]","(0.0547, 0.0595]","(0.263, 0.357]"
19,"(17.545, 19.658]","(18.581, 21.538]","(116.145, 130.616]","(1086.5, 1322.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0499, 0.0547]","(0.263, 0.357]"
20,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.198, 0.217]","(0.0595, 0.0642]","(0.546, 0.64]"
21,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0595, 0.0642]","(0.168, 0.263]"
22,"(17.545, 19.658]","(18.581, 21.538]","(116.145, 130.616]","(1086.5, 1322.25]","(0.108, 0.119]","(0.15, 0.182]","(0.213, 0.256]","(0.101, 0.121]","(0.161, 0.18]","(0.0642, 0.069]","(1.017, 1.111]"
23,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0595, 0.0642]","(0.357, 0.452]"
24,"(11.207, 13.32]","(18.581, 21.538]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0547, 0.0595]","(0.168, 0.263]"
25,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.0846, 0.117]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.069, 0.0737]","(0.168, 0.263]"
26,"(15.433, 17.545]","(18.581, 21.538]","(101.674, 116.145]","(615.0, 850.75]","(0.119, 0.13]","(0.215, 0.248]","(0.256, 0.299]","(0.121, 0.141]","(0.235, 0.254]","(0.0737, 0.0784]","(0.452, 0.546]"
27,"(13.32, 15.433]","(15.624, 18.581]","(87.203, 101.674]","(379.25, 615.0]","(0.0748, 0.0859]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0547, 0.0595]","(0.168, 0.263]"
28,"(13.32, 15.433]","(27.452, 30.409]","(72.732, 87.203]","(379.25, 615.0]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.124, 0.143]","(0.0547, 0.0595]","(0.168, 0.263]"
29,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.18, 0.198]","(0.0642, 0.069]","(0.168, 0.263]"
30,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0854, 0.128]","(0.0402, 0.0604]","(0.18, 0.198]","(0.0595, 0.0642]","(0.168, 0.263]"
31,"(9.094, 11.207]","(18.581, 21.538]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.143, 0.161]","(0.0642, 0.069]","(0.357, 0.452]"
32,"(9.094, 11.207]","(21.538, 24.495]","(58.261, 72.732]","(141.142, 379.25]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.198, 0.217]","(0.0595, 0.0642]","(0.263, 0.357]"
33,"(13.32, 15.433]","(21.538, 24.495]","(101.674, 116.145]","(615.0, 850.75]","(0.0969, 0.108]","(0.215, 0.248]","(0.256, 0.299]","(0.0805, 0.101]","(0.198, 0.217]","(0.069, 0.0737]","(0.168, 0.263]"
34,"(17.545, 19.658]","(27.452, 30.409]","(116.145, 130.616]","(850.75, 1086.5]","(0.0969, 0.108]","(0.117, 0.15]","(0.128, 0.171]","(0.0805, 0.101]","(0.161, 0.18]","(0.0547, 0.0595]","(0.357, 0.452]"
35,"(13.32, 15.433]","(30.409, 33.366]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.124, 0.143]","(0.0595, 0.0642]","(0.263, 0.357]"
36,"(17.545, 19.658]","(21.538, 24.495]","(116.145, 130.616]","(850.75, 1086.5]","(0.0859, 0.0969]","(0.182, 0.215]","(0.213, 0.256]","(0.0805, 0.101]","(0.161, 0.18]","(0.069, 0.0737]","(0.923, 1.017]"
37,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0859, 0.0969]","(0.15, 0.182]","(0.128, 0.171]","(0.0402, 0.0604]","(0.198, 0.217]","(0.069, 0.0737]","(0.357, 0.452]"
38,"(11.207, 13.32]","(12.667, 15.624]","(72.732, 87.203]","(379.25, 615.0]","(0.0637, 0.0748]","(0.0191, 0.052]","(-0.000427, 0.0427]","(-0.000201, 0.0201]","(0.143, 0.161]","(0.0595, 0.0642]","(0.263, 0.357]"
39,"(13.32, 15.433]","(12.667, 15.624]","(87.203, 101.674]","(615.0, 850.75]","(0.0748, 0.0859]","(0.0191, 0.052]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0499, 0.0547]","(0.168, 0.263]"
40,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.108, 0.119]","(0.117, 0.15]","(0.128, 0.171]","(0.0805, 0.101]","(0.198, 0.217]","(0.069, 0.0737]","(0.357, 0.452]"
41,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.161, 0.18]","(0.0595, 0.0642]","(0.168, 0.263]"
42,"(19.658, 21.771]","(18.581, 21.538]","(130.616, 145.087]","(1086.5, 1322.25]","(0.0969, 0.108]","(0.15, 0.182]","(0.171, 0.213]","(0.121, 0.141]","(0.198, 0.217]","(0.0595, 0.0642]","(0.64, 0.734]"
43,"(13.32, 15.433]","(24.495, 27.452]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.0846, 0.117]","(0.0427, 0.0854]","(0.0402, 0.0604]","(0.143, 0.161]","(0.0595, 0.0642]","(0.357, 0.452]"

In [97]:
x = df.iloc[:, 0:10]
y =df.iloc[: ,-1]

In [98]:
x = OrdinalEncoder().fit_transform(x)
y  =LabelEncoder().fit_transform(y)

In [99]:
select = SelectKBest( lambda x, y : mutual_info_classif(x,y , discrete_features= True), k =5)

In [100]:
select.fit_transform(x,y)

array([[0., 5., 4., 4., 5.],
       [4., 2., 3., 4., 1.],
       [0., 3., 1., 1., 3.],
       [5., 1., 0., 1., 3.],
       [1., 3., 2., 2., 2.],
       [0., 3., 2., 3., 3.],
       [0., 0., 0., 0., 3.],
       [5., 2., 1., 1., 5.],
       [0., 3., 2., 3., 3.],
       [0., 4., 4., 4., 3.],
       [1., 4., 2., 4., 4.],
       [3., 2., 2., 3., 2.],
       [0., 4., 3., 3., 7.],
       [0., 1., 0., 0., 1.],
       [5., 1., 0., 0., 0.],
       [5., 0., 0., 0., 2.],
       [1., 2., 1., 2., 1.],
       [0., 1., 0., 1., 3.],
       [2., 2., 2., 4., 3.],
       [3., 1., 1., 2., 1.],
       [0., 0., 0., 1., 4.],
       [5., 0., 0., 0., 1.],
       [3., 4., 5., 5., 2.],
       [0., 2., 1., 1., 2.],
       [0., 0., 0., 0., 1.],
       [0., 2., 0., 1., 2.],
       [2., 6., 6., 6., 6.],
       [1., 1., 0., 1., 3.],
       [1., 0., 0., 0., 0.],
       [5., 1., 0., 0., 3.],
       [1., 2., 2., 2., 3.],
       [5., 1., 1., 1., 1.],
       [5., 1., 0., 0., 4.],
       [1., 6., 6., 4., 4.],
       [3., 3., 3., 4., 2.],
       [1., 1., 0., 1., 0.],
       [3., 5., 5., 4., 2.],
       [0., 4., 3., 2., 4.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 2.],
       [1., 3., 3., 4., 4.],
       [1., 2., 0., 1., 2.],
       [4., 4., 4., 6., 4.],
       [1., 2., 1., 2., 1.]])

## Using chi2 especially for cat fea and cat target

In [101]:
select = SelectKBest( chi2, k =5)

In [102]:
select.fit_transform(x,y)

array([[5., 2., 5., 4., 4.],
       [1., 0., 2., 3., 4.],
       [4., 2., 3., 1., 1.],
       [3., 1., 1., 0., 1.],
       [5., 2., 3., 2., 2.],
       [5., 2., 3., 2., 3.],
       [4., 2., 0., 0., 0.],
       [3., 1., 2., 1., 1.],
       [4., 2., 3., 2., 3.],
       [5., 2., 4., 4., 4.],
       [5., 3., 4., 2., 4.],
       [1., 4., 2., 2., 3.],
       [4., 2., 4., 3., 3.],
       [4., 2., 1., 0., 0.],
       [3., 1., 1., 0., 0.],
       [3., 1., 0., 0., 0.],
       [5., 3., 2., 1., 2.],
       [4., 2., 1., 0., 1.],
       [0., 4., 2., 2., 4.],
       [1., 0., 1., 1., 2.],
       [4., 2., 0., 0., 1.],
       [3., 1., 0., 0., 0.],
       [1., 0., 4., 5., 5.],
       [4., 2., 2., 1., 1.],
       [4., 2., 0., 0., 0.],
       [4., 2., 2., 0., 1.],
       [0., 3., 6., 6., 6.],
       [5., 2., 1., 0., 1.],
       [4., 2., 0., 0., 0.],
       [3., 1., 1., 0., 0.],
       [5., 2., 2., 2., 2.],
       [3., 1., 1., 1., 1.],
       [3., 1., 1., 0., 0.],
       [0., 3., 6., 6., 4.],
       [1., 4., 3., 3., 4.],
       [4., 2., 1., 0., 1.],
       [1., 4., 5., 5., 4.],
       [4., 2., 4., 3., 2.],
       [4., 2., 0., 0., 0.],
       [5., 3., 0., 0., 1.],
       [5., 2., 3., 3., 4.],
       [5., 2., 2., 0., 1.],
       [2., 0., 4., 4., 6.],
       [5., 2., 2., 1., 2.]])